### ISSUE TITLE
ePadjs deployed by docker does not work

### ISSUE THREAD

**Issue by minhhungvu17** [RubinLab/epad-dist#1]
Hi Rubin Lab, I'm trying to deploy ePad for medical image annotation. However, there is a small problem

##  Problem 
ePadjs does not work after installation via dockers.

## Steps to reproduce

1.  Open the ports:

- 3000
- 8080
- 8090
- 8899

2. Install docker
3. Replace http://epad-build.stanford.edu with localhost ip in the files mentioned in the  installation guide
4.  Run docker-compose up --build -d

## Expected Behavior
ePadjs web runs and goes to login page

## Actual behavior
ePadjs does not direct to login page to access private modules

ePadjs running on Chrome
<img width="1552" alt="Capture d’écran 2019-12-19 à 4 12 15 PM" src="https://user-images.githubusercontent.com/33442949/71160540-5c699800-227a-11ea-8a42-e1ab75e5e025.png">
Docker checking
<img width="850" alt="Capture d’écran 2019-12-19 à 4 11 47 PM" src="https://user-images.githubusercontent.com/33442949/71160554-6095b580-227a-11ea-9b57-8ae553438224.png">

Thank you for your help!

**Comment by emelalkim** [comment]
Hi,
I think this issue is actually related to the epadlite beta distribution files in ftp not this project. This project is focused on automating the edits on the configuration files.
I suggest you use this project to generate the configuration files for your system as your issue is most probably caused by problems in your configuration files. If you use the sample yml file in this project and edit the host and required credentials, you can get the daily build. 
~~If you want to use the beta images instead, you can check the readme and modify mode and image attributes for each module (Let us know if you need help with that)~~ Actually, these files (docker-compose) won't work with beta images since we changed the code directory structure in the images to run with non root user. We'll have the docker images of the first release soon.
Nonetheless, your issue is most probably caused by the wrong value in production_keycloak.json file. In chrome you can right click, open Inspect and check console and network to see what is the issue.

**Comment by minhhungvu17** [comment]
@emelalkim thank you so much for your suggestion. The issue was solved so I will close this ticket. Regards.
